### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by evanessa234** [evanessa234/enrolld#1]
- [ ] Add JWT authentication.
- [ ] Write clean and asynchronous routes.
- [ ] Proper error handlers and logging.
- [ ] Extensive documentation.
